// <auto-generated />
namespace P.I.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CPF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CPF));
        
        string IMigrationMetadata.Id
        {
            get { return "202302131429564_CPF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
